# Generated by Django 5.2.1 on 2025-06-16 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', help_text='Nivel de dificultad de la actividad', max_length=20)),
                ('type', models.CharField(choices=[('choice', 'Opción múltiple'), ('fill_in', 'Completar'), ('matching', 'Unir'), ('order', 'Ordenar')], default='choice', help_text='Tipo de actividad', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('is_multiple', models.BooleanField(default=False, help_text='Marcar True si permite seleccionar múltiples opciones')),
            ],
            options={
                'db_table': 'choice_activity',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='FillInTheBlankActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('text', models.TextField(help_text="Texto con marcadores de posición, p.ej. 'La capital de Francia es {{blank}}'")),
                ('correct_answers', models.JSONField(help_text="Diccionario de índices y respuestas correctas, p.ej. {'0': 'París'}")),
            ],
            options={
                'db_table': 'fill_in_the_blank_activity',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='MatchingActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
            ],
            options={
                'db_table': 'matching_activity',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='WordOrderingActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('sentence', models.TextField(help_text="Oración correcta, p.ej. 'El gato está durmiendo'")),
            ],
            options={
                'db_table': 'word_ordering_activity',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('activity_id', models.PositiveIntegerField()),
                ('response_data', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_answer',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='activities.choiceactivity')),
            ],
            options={
                'db_table': 'choice',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(max_length=255)),
                ('right', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='activities.matchingactivity')),
            ],
            options={
                'db_table': 'matching_pair',
            },
        ),
    ]
