# Generated by Django 5.2.5 on 2025-08-15 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_module_alter_useranswer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Exam Activity',
                'verbose_name_plural': 'Exam Activities',
                'db_table': 'exam_activity',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='choiceactivity',
            options={'verbose_name': 'Choice Activity', 'verbose_name_plural': 'Choice Activities'},
        ),
        migrations.AlterModelOptions(
            name='fillintheblankactivity',
            options={'verbose_name': 'Fill in the Blank Activity', 'verbose_name_plural': 'Fill in the Blank Activities'},
        ),
        migrations.AlterModelOptions(
            name='matchingactivity',
            options={'verbose_name': 'Matching Activity', 'verbose_name_plural': 'Matching Activities'},
        ),
        migrations.AlterModelOptions(
            name='matchingpair',
            options={'verbose_name': 'Matching Pair', 'verbose_name_plural': 'Matching Pairs'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'User Answer', 'verbose_name_plural': 'User Answers'},
        ),
        migrations.AlterModelOptions(
            name='wordorderingactivity',
            options={'verbose_name': 'Word Ordering Activity', 'verbose_name_plural': 'Word Ordering Activities'},
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de puntos que otorga la actividad'),
        ),
        migrations.AddField(
            model_name='matchingpair',
            name='is_vocabulary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='activities.activity'),
        ),
    ]
