# Generated by Django 5.2.5 on 2025-08-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_examactivity_alter_activity_options_and_more'),
        ('content', '0004_exam_examattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='exam_attempt',
            field=models.ForeignKey(blank=True, help_text='Si la respuesta pertenece a un examen, referencia el intento.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.examattempt'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'activity', 'is_correct'], name='user_answer_user_id_3c3589_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['exam_attempt', 'activity'], name='user_answer_exam_at_41b115_idx'),
        ),
        migrations.AddField(
            model_name='examactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_items', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='examactivity',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_items', to='content.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='examactivity',
            unique_together={('exam', 'activity')},
        ),
    ]
