# Generated by Django 5.2.5 on 2025-08-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', max_length=20),
        ),
    ]
