# Generated by Django 5.2.1 on 2025-06-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vocabulary',
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/photos/'),
        ),
        migrations.CreateModel(
            name='StudentLanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)'), ('N', 'Native')], default='A1', max_length=2)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_proficiencies', to='languages.language')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_proficiencies', to='people.student')),
            ],
            options={
                'verbose_name': 'Student Language Proficiency',
                'verbose_name_plural': 'Student Language Proficiencies',
                'db_table': 'student_language_proficiencies',
                'unique_together': {('student', 'language')},
            },
        ),
    ]
