# Generated by Django 5.2.1 on 2025-07-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_student_progress_remove_student_vocabulary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
