# Generated by Django 5.2.1 on 2025-07-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_person_languages_alter_person_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
