# Generated by Django 5.2.1 on 2025-07-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_vocabulary_learned_course_module'),
        ('people', '0005_alter_person_country_alter_person_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='content.course'),
        ),
    ]
