# Generated by Django 5.2.1 on 2025-08-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='national_id',
        ),
    ]
