# Generated by Django 5.2.5 on 2025-08-15 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_exam_examattempt'),
        ('people', '0007_remove_person_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='person',
            name='has_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='active_course',
            field=models.ForeignKey(blank=True, help_text='Curso actualmente activo del estudiante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_students', to='content.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción breve sobre el estudiante.', null=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=12)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default='student', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('progress_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='people.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'indexes': [models.Index(fields=['student', 'course', 'status'], name='enrollments_student_4ec5d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='uq_enrollment_student_course'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student',), name='uq_one_active_enrollment_per_student')],
            },
        ),
    ]
