# Generated by Django 5.2.1 on 2025-08-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_remove_student_course_person_has_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.CharField(blank=True, help_text='URL o ruta de la foto de perfil.', max_length=500, null=True),
        ),
    ]
