# Generated by Django 5.2.1 on 2025-06-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='learned',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images/')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=50)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='languages.language')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/images/')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
            },
        ),
    ]
