# Generated by Django 5.2.5 on 2025-08-15 21:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_vocabulary_learned_course_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MIDTERM', 'Parcial'), ('FINAL', 'Final')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts_allowed', models.PositiveIntegerField(default=1)),
                ('pass_mark_percent', models.PositiveSmallIntegerField(default=60, help_text='Porcentaje mínimo para aprobar (0-100)')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score_points', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_attempt',
            },
        ),
    ]
