# Generated by Django 5.2.5 on 2025-08-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_useranswer_exam_attempt_and_more'),
        ('content', '0004_exam_examattempt'),
        ('people', '0008_remove_student_course_person_has_access_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', through='people.Enrollment', to='people.student'),
        ),
        migrations.AddField(
            model_name='module',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que finaliza el módulo', null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(fields=('student', 'word'), name='uq_vocab_student_word'),
        ),
        migrations.AddField(
            model_name='exam',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='in_exams', through='activities.ExamActivity', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='content.course'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.exam'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('course', 'type'), name='uniq_exam_per_course_and_type'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'user', 'status'], name='exam_attemp_exam_id_37bd45_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'user', 'attempt_number'), name='uniq_attempt_per_exam_user_number'),
        ),
    ]
